version: '3'
services:
  postgres:
    image: postgres
    container_name: bank-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@demo.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "9090:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmins
volumes:
  db-data:
  pgadmin-data: